language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

services:
  - mongodb
  - redis

before_install:
  - mongod --port 29017 --dbpath /tmp/mongodb-alt

install:
  - composer install

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mkdir /tmp/mongodb-alt
  - sleep 15

env: TRIPOD_DATASOURCE_RS2_CONFIG='{"type":"mongo","connection":"mongo:\/\/localhost:29017"}'

script: ant