language: php
sudo: false
php:
- 5.6
- 5.5
- 5.4
services:
- mongodb
- redis
before_install:
- pecl install mongodb
install:
- composer install
script: ant
notifications:
  hipchat:
    rooms:
      secure: ZVAxv+jZawDdIgLyNERg8IkK3EPZNz04OKZeUrVj55clceDXPmpYv3TC/Gw/xuR19i52HGlqFlYDMNlfl689lzJE45rhabTwMNpAch8R7p5QAKUTCZOkIRfBKPTW68dSRndJf/Y6nsf0kSdKEdgSFCced3JchhvZrScPGBoSRaI=
