language: php
php:
  - 5.5
  - 5.4
  - 5.3

services:
  - mongodb
  - redis

install:
  - composer install

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sleep 15

script: ant