language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

services:
  - mongodb
  - redis

install:
  - composer install

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mongod --port 29017 --dbpath /var/mongodb-alt --fork --logpath /var/log/mongodb-alt.log
  - sleep 15

env: TRIPOD_DATASOURCE_RS2_CONFIG={"type":"mongo","connection":"mongo://127.0.0.1:29017"}

script: ant