language: php
php:
  - 5.4
  - 5.3
  - 5.2
install:
  - composer install
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit ./test/unit